<a href="https://colab.research.google.com/github/VARADMHETARRAHUL/NumpyTutorial/blob/main/Numpy_Tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

The Basics

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[3.0,2.0,1.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [7]:
#Get dimension
a.ndim

1

In [9]:
#Get shape
b.shape

(3, 3)

In [10]:
#Get type
a.dtype

dtype('int64')

In [11]:
#Get size
a.itemsize

8

In [14]:
#Get total size
a.nbytes

24

Accessing or changing specific elements, rows, columns, etc.

In [16]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
#Get a specific [r,c]
print(a[1,5])

13


In [19]:
#Get a speicifc row
print(a[0, :])

[1 2 3 4 5 6 7]


In [20]:
#Get a specific column
a[:,2]

array([ 3, 10])